[project]
name = "openfold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "claude-agent-sdk>=0.1.18",
    "modal>=1.3.0.post1",
    "python-dotenv>=1.2.1",
]
